.TH "BSModel" 3 "Wed May 4 2016" "Option Pricing Example" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BSModel \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BSModel01\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBSModel\fP (double S0_, double r_, double sigma_)"
.br
.ti -1c
.RI "void \fBGenerateSamplePath\fP (double T, int m, \fBSamplePath\fP &S)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBS0\fP"
.br
.ti -1c
.RI "double \fBr\fP"
.br
.ti -1c
.RI "double \fBsigma\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file BSModel01\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BSModel::BSModel (doubleS0_, doubler_, doublesigma_)\fC [inline]\fP"

.PP
Definition at line 37 of file BSModel01\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void BSModel::GenerateSamplePath (doubleT, intm, \fBSamplePath\fP &S)"

.PP
Definition at line 33 of file BSModel01\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "double BSModel::r"

.PP
Definition at line 34 of file BSModel01\&.h\&.
.SS "double BSModel::S0"

.PP
Definition at line 33 of file BSModel01\&.h\&.
.SS "double BSModel::sigma"

.PP
Definition at line 35 of file BSModel01\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Option Pricing Example from the source code\&.
