.TH "ExplicitMethod" 3 "Wed May 4 2016" "Option Pricing Example" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExplicitMethod \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ExplicitMethod\&.h>\fP
.PP
Inherits \fBFDMethod\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExplicitMethod\fP (\fBParabPDE\fP *PtrPDE_, int imax_, int jmax_)"
.br
.ti -1c
.RI "double \fBA\fP (int i, int j)"
.br
.ti -1c
.RI "double \fBB\fP (int i, int j)"
.br
.ti -1c
.RI "double \fBC\fP (int i, int j)"
.br
.ti -1c
.RI "double \fBD\fP (int i, int j)"
.br
.ti -1c
.RI "void \fBSolvePDE\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 6 of file ExplicitMethod\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ExplicitMethod::ExplicitMethod (\fBParabPDE\fP *PtrPDE_, intimax_, intjmax_)\fC [inline]\fP"

.PP
Definition at line 9 of file ExplicitMethod\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "double ExplicitMethod::A (inti, intj)\fC [inline]\fP"

.PP
Definition at line 12 of file ExplicitMethod\&.h\&.
.SS "double ExplicitMethod::B (inti, intj)\fC [inline]\fP"

.PP
Definition at line 15 of file ExplicitMethod\&.h\&.
.SS "double ExplicitMethod::C (inti, intj)\fC [inline]\fP"

.PP
Definition at line 18 of file ExplicitMethod\&.h\&.
.SS "double ExplicitMethod::D (inti, intj)\fC [inline]\fP"

.PP
Definition at line 21 of file ExplicitMethod\&.h\&.
.SS "void ExplicitMethod::SolvePDE ()"

.PP
Definition at line 3 of file ExplicitMethod\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Option Pricing Example from the source code\&.
