.TH "Main24.cpp" 3 "Wed May 4 2016" "Option Pricing Example" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Main24.cpp \- 
.PP
Test the option pricing code based on the Black--Scholes model\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'BSModel01\&.h'\fP
.br
\fC#include 'Options\&.h'\fP
.br
\fC#include 'BSEq\&.h'\fP
.br
\fC#include 'ExplicitMethod\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file is the first driver file implementing a solution to the Black--Scholes model, using a standard finite differences approach, on a nodal grid to compute the price of a put option based on its maturity date, and based on the value of its underlying asset\&.
.PP
\fBWarning:\fP
.RS 4
This code is also listed and fully explained in the book **Numerical Methods in Finance with C++** by Maciej Capiński and Tomasz Zastawniak, published in September 2012\&.
.RE
.PP
\fBAuthor:\fP
.RS 4
: Eduardo J\&. Sanchez (ejspeiro) - ejspeiro at gmail dot com 
.RE
.PP

.PP
Definition in file \fBMain24\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Definition at line 72 of file Main24\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Option Pricing Example from the source code\&.
