.TH "Options.cpp" 3 "Wed May 4 2016" "Option Pricing Example" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Options.cpp \- 
.PP
Implementation of classes to represent an option an a put option\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <cmath>\fP
.br
\fC#include 'Options\&.h'\fP
.br

.SH "Detailed Description"
.PP 
We write out classes which will be used to store the coefficients and boundary conditions in order to price options under the Black--Scholes equation\&. We represent an option as an abstract class\&. Its methods will the overridden by the put option class
.PP
\fBWarning:\fP
.RS 4
This code is also listed and fully explained in the book **Numerical Methods in Finance with C++** by Maciej Capiński and Tomasz Zastawniak, published in September 2012\&.
.RE
.PP
\fBAuthor:\fP
.RS 4
: Eduardo J\&. Sanchez (ejspeiro) - ejspeiro at gmail dot com 
.RE
.PP

.PP
Definition in file \fBOptions\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Option Pricing Example from the source code\&.
