.TH "page_readme" 3 "Wed May 4 2016" "Option Pricing Example" \" -*- nroff -*-
.ad l
.nh
.SH NAME
page_readme \- Read Me File 

.PP
.nf
# OptionPricing

This repository contains object-oriented code implementing numerical methods for
option pricing.

This code is also listed and fully explained in the book **Numerical Methods in
Finance with C++** by Maciej Capiński and Tomasz Zastawniak, published in
September 2012.

This code is a minimally-complete example intended for research and modeling.
This is not intended to be production code.

.fi
.PP
 
