.TH "page_architectures" 3 "Wed May 4 2016" "Option Pricing Example" \" -*- nroff -*-
.ad l
.nh
.SH NAME
page_architectures \- Tested Architectures 
The following architectures have provided a correct execution of this code:
.PP
.PP
.nf
1. Intel(R) Core(TM) i7-4600U CPU 2.10 GHz 4096 KB of cache and a stepping of 1.
   Linux 3.16.7-29-desktop #1 SMP PREEMPT (6be6a97) x86_64 GNU/Linux
   openSUSE 13.2 (Harlequin) (x86_64)
   gcc (SUSE Linux) 4.8.3 20140627 [gcc-4_8-branch revision 212064]
.fi
.PP
 
