.TH "ParabPDE" 3 "Wed May 4 2016" "Option Pricing Example" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParabPDE \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ParabPDE\&.h>\fP
.PP
Inherited by \fBBSEq\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual double \fBa\fP (double t, double x)=0"
.br
.ti -1c
.RI "virtual double \fBb\fP (double t, double x)=0"
.br
.ti -1c
.RI "virtual double \fBc\fP (double t, double x)=0"
.br
.ti -1c
.RI "virtual double \fBd\fP (double t, double x)=0"
.br
.ti -1c
.RI "virtual double \fBf\fP (double x)=0"
.br
.ti -1c
.RI "virtual double \fBfu\fP (double t)=0"
.br
.ti -1c
.RI "virtual double \fBfl\fP (double t)=0"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBT\fP"
.br
.ti -1c
.RI "double \fBxl\fP"
.br
.ti -1c
.RI "double \fBxu\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 34 of file ParabPDE\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual double ParabPDE::a (doublet, doublex)\fC [pure virtual]\fP"

.PP
Implemented in \fBBSEq\fP\&.
.SS "virtual double ParabPDE::b (doublet, doublex)\fC [pure virtual]\fP"

.PP
Implemented in \fBBSEq\fP\&.
.SS "virtual double ParabPDE::c (doublet, doublex)\fC [pure virtual]\fP"

.PP
Implemented in \fBBSEq\fP\&.
.SS "virtual double ParabPDE::d (doublet, doublex)\fC [pure virtual]\fP"

.PP
Implemented in \fBBSEq\fP\&.
.SS "virtual double ParabPDE::f (doublex)\fC [pure virtual]\fP"

.PP
Implemented in \fBBSEq\fP\&.
.SS "virtual double ParabPDE::fl (doublet)\fC [pure virtual]\fP"

.PP
Implemented in \fBBSEq\fP\&.
.SS "virtual double ParabPDE::fu (doublet)\fC [pure virtual]\fP"

.PP
Implemented in \fBBSEq\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double ParabPDE::T"

.PP
Definition at line 37 of file ParabPDE\&.h\&.
.SS "double ParabPDE::xl"

.PP
Definition at line 38 of file ParabPDE\&.h\&.
.SS "double ParabPDE::xu"

.PP
Definition at line 39 of file ParabPDE\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Option Pricing Example from the source code\&.
