ExplicitMethod
ExplicitMethod::ExplicitMethod(ParabPDE *PtrPDE_, int imax_, int jmax_)
double ExplicitMethod::A(int i, int j)
References FDMethod::dt, FDMethod::b, FDMethod::a, FDMethod::dx.
Referenced by SolvePDE.
double ExplicitMethod::B(int i, int j)
References FDMethod::dt, FDMethod::c, FDMethod::a, FDMethod::dx.
Referenced by SolvePDE.
double ExplicitMethod::C(int i, int j)
References FDMethod::dt, FDMethod::b, FDMethod::a, FDMethod::dx.
Referenced by SolvePDE.
double ExplicitMethod::D(int i, int j)
References FDMethod::dt, FDMethod::d.
Referenced by SolvePDE.
void ExplicitMethod::SolvePDE()
References FDMethod::jmax, FDMethod::V, FDMethod::imax, FDMethod::f, FDMethod::fl, FDMethod::fu, A, B, C, D.
Referenced by main.