FDMethod
ParabPDE* FDMethod::PtrPDE
Referenced by FDMethod, v.
int FDMethod::imax
Referenced by ExplicitMethod::SolvePDE, FDMethod.
int FDMethod::jmax
Referenced by ExplicitMethod::SolvePDE, FDMethod.
double FDMethod::dx
Referenced by ExplicitMethod::A, ExplicitMethod::B, ExplicitMethod::C, FDMethod, v.
double FDMethod::dt
Referenced by ExplicitMethod::A, ExplicitMethod::B, ExplicitMethod::C, ExplicitMethod::D, FDMethod, v.
vector<Vector> FDMethod::V
Referenced by ExplicitMethod::SolvePDE, FDMethod, v.
FDMethod::FDMethod(ParabPDE *PtrPDE_, int imax_, int jmax_)
References PtrPDE, imax, jmax, dx, ParabPDE::xu, ParabPDE::xl, dt, ParabPDE::T, V.
double FDMethod::t(double i)
Referenced by v.
double FDMethod::x(int j)
References ParabPDE::xl.
Referenced by v.
double FDMethod::a(double i, int j)
References ParabPDE::a.
Referenced by ExplicitMethod::A, ExplicitMethod::B, ExplicitMethod::C.
double FDMethod::b(double i, int j)
References ParabPDE::b.
Referenced by ExplicitMethod::A, ExplicitMethod::C.
double FDMethod::c(double i, int j)
References ParabPDE::c.
Referenced by ExplicitMethod::B.
double FDMethod::d(double i, int j)
References ParabPDE::d.
Referenced by ExplicitMethod::D.
double FDMethod::f(int j)
References ParabPDE::f.
Referenced by ExplicitMethod::SolvePDE.
double FDMethod::fu(int i)
References ParabPDE::fu.
Referenced by ExplicitMethod::SolvePDE.
double FDMethod::fl(int i)
References ParabPDE::fl.
Referenced by ExplicitMethod::SolvePDE.
double FDMethod::v(double t, double x)
References dt, PtrPDE, ParabPDE::xl, dx, t, x, V.
Referenced by main.