ParabPDE
double ParabPDE::T
Referenced by BSEq::BSEq, FDMethod::FDMethod.
double ParabPDE::xl
Referenced by BSEq::BSEq, FDMethod::FDMethod, FDMethod::v, FDMethod::x.
double ParabPDE::xu
Referenced by BSEq::BSEq, FDMethod::FDMethod.
virtual double ParabPDE::a(double t, double x)=0
Referenced by FDMethod::a.
virtual double ParabPDE::b(double t, double x)=0
Referenced by FDMethod::b.
virtual double ParabPDE::c(double t, double x)=0
Referenced by FDMethod::c.
virtual double ParabPDE::d(double t, double x)=0
Referenced by FDMethod::d.
virtual double ParabPDE::f(double x)=0
Referenced by FDMethod::f.
virtual double ParabPDE::fu(double t)=0
Referenced by FDMethod::fu.
virtual double ParabPDE::fl(double t)=0
Referenced by FDMethod::fl.